# Generated by Django 5.1.5 on 2025-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size'), ('Material', 'Material')], max_length=100),
        ),
    ]
