# Generated by Django 5.1.5 on 2025-01-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
